version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"

    ports:
      - 5000:5000

    volumes:
      - ./datatrain/Thai.traineddata:/usr/share/tesseract-ocr/4.00/tessdata/Thai.traineddata
