#!/usr/bin/env python3
import argparse

# Instantiate the parser
parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('--token', type=str,
                    help='token')
parser.add_argument('--name', type=str,
                    help='user/repostory')
args = parser.parse_args()
import issueprocess.app as load
load.getByname(args.token,args.name)
