#!/usr/bin/env python3
import argparse

# Instantiate the parser
parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('--user', type=str,
                    help='user of database')
parser.add_argument('--password', type=str,
                    help='password of database')
parser.add_argument('--host', type=str,
                    help='host of database')
parser.add_argument('--port', type=str,
                    help='port of database')
parser.add_argument('--database', type=str,
                    help='database of database')
parser.add_argument('--table', type=str,
                    help='tabel of database')
args = parser.parse_args()
print(args.user)
print(args.password)
print(args.host)
print(args.port)
print(args.database)
print(args.table)

import issueprocess.datasql as load
preTitle,preDescription,preLabel = load.loaddata(args.user,args.password,args.host,args.port,args.database,args.table)
import issueprocess.splitClass as spl
listbug,listdoc,listdup,listenh,listgood,listhelp,listinv = spl.splitclass(preTitle,preDescription,preLabel)

import issueprocess.train_svm as acc
acc.accepdata(listbug,listdoc,listdup,listenh,listgood,listhelp,listinv)
